"""BrainTrade LP template sections — replicated from the Figma file
5t066Ac9yDEqdJ7fvN05Pv ("BrainTrade LP Template", page "New Template /
17.03.2026"): the desktop/tablet/mobile frames define the layout, the
component sets on the left of that page supply the per-language MATERIALS —
extracted verbatim into each section's `texts` (languages: en, pt, es, ja,
th, vi, ar, zh, it, pl, sv, fr, de where the set provides them).

Design tokens (via the BrainTrade brand): primary #FF7532 (orange CTAs),
accent #070851 (navy headings), muted #707070 body text, card border #DDE1E6,
Urbanist typography (google-fonts export mode loads it; otherwise the system
stack applies). AUTO-GENERATED by scratchpad/gen_bt_sections.py — regenerate
rather than hand-editing the texts.
"""

# Shared shell for every BrainTrade section (kept local so admins can clone
# any bt-* section without dragging hidden dependencies along).
_FONT = "font-family:'Urbanist',var(--lp-font)"

BRAINTRADE_SECTIONS = [
 {
  "key": "bt-header",
  "name": "BT / Header",
  "category": "braintrade",
  "position": 200,
  "html": "<section class=\"lp-sec-bt-header\">\n <div class=\"lp-wrap bth-row\"><img class=\"bth-logo\" data-lp-img=\"logo\" src=\"\" alt=\"BrainTrade\"></div>\n</section>",
  "css": ".lp-sec-bt-header{background:#fff;padding:18px 0}\n.lp-sec-bt-header .bth-row{display:flex;justify-content:flex-end}\n.lp-sec-bt-header .bth-logo{height:34px;object-fit:contain}",
  "texts": {
   "en": {}
  }
 },
 {
  "key": "bt-hero-form",
  "name": "BT / Hero + form",
  "category": "braintrade",
  "position": 205,
  "html": "<section class=\"lp-sec-bt-hero-form\">\n <div class=\"lp-wrap bthf-grid\">\n  <div class=\"bthf-media\"><img data-lp-img=\"creative\" src=\"\" alt=\"\"></div>\n  <form class=\"bthf-card\" data-lp-form>\n   <h1 class=\"bthf-title\" data-lp-text=\"title\">Start Your Trading Education With a Personal Trainer</h1>\n   <input class=\"bthf-in\" type=\"text\" name=\"name\" data-lp-text=\"ph_name\" placeholder=\"Full name\" required>\n   <input class=\"bthf-in\" type=\"email\" name=\"email\" data-lp-text=\"ph_email\" placeholder=\"E-Mail\" required>\n   <input class=\"bthf-in\" type=\"tel\" name=\"phone\" data-lp-text=\"ph_phone\" placeholder=\"Phone number\" required>\n   <label class=\"bthf-consent\"><input type=\"checkbox\" name=\"consent\" required> <span data-lp-text=\"consent\">I agree to the Privacy Policy and Terms &amp; Conditions</span></label>\n   <button class=\"bthf-btn\" type=\"submit\" data-lp-text=\"submit\">Start My Coaching Journey</button>\n   <p class=\"bthf-trust\" data-lp-text=\"trust\">✓ Free to join ✓ No experience required ✓ 1-on-1 guidance included</p>\n  </form>\n </div>\n</section>",
  "css": ".lp-sec-bt-hero-form{background:#fff;padding:28px 0 56px;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-hero-form .bthf-grid{display:grid;grid-template-columns:1.35fr 1fr;gap:40px;align-items:stretch}\n.lp-sec-bt-hero-form .bthf-media{border-radius:24px;background:#F8D8CC;min-height:520px;overflow:hidden}\n.lp-sec-bt-hero-form .bthf-media img{width:100%;height:100%;object-fit:cover;display:block}\n.lp-sec-bt-hero-form .bthf-card{display:flex;flex-direction:column;gap:12px;padding:8px 0}\n.lp-sec-bt-hero-form .bthf-title{color:var(--lp-accent);font-size:1.55rem;font-weight:700;line-height:1.3;margin:0 0 10px;text-align:center}\n.lp-sec-bt-hero-form .bthf-in{border:1px solid #DDE1E6;border-radius:10px;padding:.9rem 1rem;font-size:.98rem;font-family:inherit}\n.lp-sec-bt-hero-form .bthf-consent{display:flex;gap:.55rem;font-size:.8rem;color:var(--lp-muted);align-items:flex-start;line-height:1.45}\n.lp-sec-bt-hero-form .bthf-btn{background:var(--lp-primary);color:#fff;border:0;border-radius:10px;padding:1rem;font-size:1.05rem;font-weight:700;cursor:pointer;font-family:inherit}\n.lp-sec-bt-hero-form .bthf-trust{color:var(--lp-accent);font-size:.85rem;text-align:center;margin:4px 0 0;white-space:pre-line}\n@media (max-width:1199px){.lp-sec-bt-hero-form .bthf-grid{grid-template-columns:1fr 1fr;gap:24px}}\n@media (max-width:575px){.lp-sec-bt-hero-form{padding:16px 0 40px}.lp-sec-bt-hero-form .bthf-grid{grid-template-columns:1fr}.lp-sec-bt-hero-form .bthf-media{min-height:260px}}",
  "texts": {
   "en": {
    "title": "Start Your Trading Education With a Personal Trainer",
    "ph_name": "Full name",
    "ph_email": "E-Mail",
    "ph_phone": "Phone number",
    "consent": "I agree to the Privacy Policy and Terms & Conditions",
    "submit": "Start My Coaching Journey",
    "trust": "✓ Free to join ✓ No experience required  ✓ 1-on-1 guidance included"
   },
   "pt": {
    "title": "Comece Sua Jornada com um Coach Pessoal",
    "ph_name": "Nome completo",
    "ph_email": "E-mail",
    "ph_phone": "Número de telefone",
    "consent": "Concordo com a Política de Privacidade e os Termos e Condições",
    "submit": "Iniciar Minha Jornada",
    "trust": "✓ Inscrição gratuita ✓ Sem experiência prévia ✓ Orientação individual incluída"
   },
   "ja": {
    "title": "専任メンターと共にあなたのトレーディング教育を始めましょう",
    "ph_name": "フルネーム",
    "ph_email": "Eメール",
    "ph_phone": "電話番号",
    "consent": "利用規約およびプライバシーポリシーに同意します。",
    "submit": "登録して始める",
    "trust": "✓ 参加無料 ✓ 経験不問  ✓ 1対1の指導が含まれています"
   },
   "th": {
    "title": " เริ่มเรียนเทรดกับโค้ชส่วนตัว",
    "ph_name": "ชื่อเต็ม",
    "ph_email": "อีเมล",
    "ph_phone": "หมายเลขโทรศัพท์",
    "consent": "ฉันยอมรับ ข้อกำหนดและเงื่อนไข และ นโยบายความเป็นส่วนตัว แล้ว",
    "submit": "ริ่มต้นกับโค้ชของฉัน",
    "trust": " สมัครฟรี ✓ ไม่ต้องมีประสบการณ์ ✓ รวมคำแนะนำแบบ 1-ต่อ-1"
   },
   "vi": {
    "title": "Bắt đầu giáo dục giao dịch của bạn với một huấn luyện viên cá nhân",
    "ph_name": "Họ và tên đầy đủ",
    "ph_email": "E-Mail",
    "ph_phone": "Số điện thoại",
    "consent": "Tôi đồng ý với các Điều khoản và Điều kiện cũng như Chính sách quyền riêng tư.",
    "submit": "Bắt đầu hành trình huấn luyện của tôi",
    "trust": "✓ Miễn phí tham gia ✓ Không yêu cầu kinh nghiệm ✓ Đã bao gồm hướng dẫn 1-kèm-1"
   },
   "ar": {
    "title": "ابدأ تعليمك في التداول مع مدرب شخصي",
    "ph_name": "البريد الإلكتروني",
    "ph_email": "الاسم الكامل",
    "ph_phone": "البريد الإلكتروني",
    "consent": "رقم الهاتف",
    "submit": "أوافق على سياسة الخصوصية والشروط والأحكام",
    "trust": "ابدأ رحلتي في التدريب"
   },
   "zh": {
    "title": "与专属导师一起，开启您的交易教育之旅",
    "ph_name": "全名",
    "ph_email": "电子邮件",
    "ph_phone": "电话号码",
    "consent": "我同意隐私政策及用户条款",
    "submit": "开始我的辅导之旅",
    "trust": "✓ 免费加入 ✓ 无需经验 ✓ 包含一对一指导"
   },
   "it": {
    "title": "Inizia la tua formazione nel trading con un coach personale",
    "ph_name": "Nome completo",
    "ph_email": "Email",
    "ph_phone": "Numero di telefono",
    "consent": "Accetto i Termini e Condizioni e l'Informativa sulla Privacy.",
    "submit": "Inizia il mio percorso di coaching",
    "trust": "✓ Iscrizione gratuita ✓ Nessuna esperienza richiesta ✓ Guida 1-a-1 inclusa"
   },
   "pl": {
    "title": "Rozpocznij swoją naukę tradingu z osobistym coachem",
    "ph_name": "Pełne imię i nazwisko",
    "ph_email": "E-mail",
    "ph_phone": "Numer telefonu",
    "consent": "Zgadzam się z Regulaminem i Polityką prywatności.",
    "submit": "Chcę rozpocząć swój coaching",
    "trust": "✓ Darmowe członkostwo ✓ Bez wymaganego doświadczenia ✓ Indywidualne wsparcie w cenie"
   },
   "sv": {
    "title": "Börja din handelsutbildning med en personlig mentor",
    "ph_name": "Fullständigt namn",
    "ph_email": "E-post",
    "ph_phone": "Telefonnummer",
    "consent": "Jag godkänner användarvillkoren och sekretesspolicyn.",
    "submit": "Starta min utbildning",
    "trust": "✓ Gratis att börja ✓ Ingen erfarenhet krävs  ✓ 1-mot-1 vägledning ingår"
   },
   "fr": {
    "title": "Commencez votre carrière de trading Avec un mentor personnel",
    "ph_name": "Nom complet",
    "ph_email": "E-Mail",
    "ph_phone": "Numéro de téléphone",
    "consent": "J’accepte les Conditions générales et la Politique de confidentialité.",
    "submit": "Commencez mon parcours de coaching",
    "trust": "✓ Gratuit à rejoindre ✓ Aucune expérience requise ✓ Accompagnement individuel inclus"
   },
   "de": {
    "title": "Beginnen Sie Ihre Handelsausbildung Mit einem persönlichen Trainer",
    "ph_name": "Vollständiger Name",
    "ph_email": "E-Mail",
    "ph_phone": "Telefonnummer",
    "consent": "Ich stimme den Allgemeinen Geschäftsbedingungen und der Datenschutzerklärung zu.",
    "submit": "Beginnen Sie Ihre Coaching-Reise",
    "trust": "✓ Kostenlos beitreten ✓ Keine Erfahrung erforderlich ✓ 1-zu-1 Anleitung inklusive "
   }
  }
 },
 {
  "key": "bt-steps",
  "name": "BT / 3 simple steps",
  "category": "braintrade",
  "position": 210,
  "html": "<section class=\"lp-sec-bt-steps\">\n <div class=\"lp-wrap\">\n  <h2 class=\"bts-title\" data-lp-text=\"title\">Join BrainTrade In 3 Simple Steps</h2>\n  <div class=\"bts-grid\">\n   <!--lp-repeat:steps--><div class=\"bts-card\"><div class=\"bts-icon\"><img data-lp-img=\"icon\" src=\"\" alt=\"\"></div><h3 class=\"bts-card-title\" data-lp-text=\"title\">1. Sign up and learn</h3><p class=\"bts-card-text\" data-lp-rich=\"text\">Register today and gain immediate access to our highly-rated online investment academy.</p></div><!--/lp-repeat:steps-->\n  </div>\n </div>\n</section>",
  "css": ".lp-sec-bt-steps{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-steps .bts-title{color:var(--lp-accent);font-size:1.9rem;font-weight:700;text-align:center;margin:0 0 34px}\n.lp-sec-bt-steps .bts-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:22px}\n.lp-sec-bt-steps .bts-card{background:#fff;border:1px solid #DDE1E6;border-radius:16px;padding:26px;text-align:center}\n.lp-sec-bt-steps .bts-icon{height:64px;display:flex;align-items:center;justify-content:center;margin-bottom:14px}\n.lp-sec-bt-steps .bts-icon img{max-height:64px;object-fit:contain}\n.lp-sec-bt-steps .bts-card-title{color:var(--lp-accent);font-size:1.05rem;font-weight:600;margin:0 0 8px}\n.lp-sec-bt-steps .bts-card-text{color:var(--lp-muted);font-size:.92rem;line-height:1.55;margin:0}\n@media (max-width:575px){.lp-sec-bt-steps .bts-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {
    "title": "Join BrainTrade In 3 Simple Steps",
    "steps.0.title": "1. Sign up and learn",
    "steps.0.text": "Register today and gain immediate access to our highly-rated online investment academy.",
    "steps.1.title": "2. One-on-one phone coaching",
    "steps.1.text": "After you register, your dedicated coach will call you for a free session to explain why mastering online investing is essential.",
    "steps.2.title": "3. Learn all about the markets",
    "steps.2.text": "Start your online trading education journey and get insights on the financial markets and the tools you need to conquer them."
   },
   "pt": {
    "title": "Junte-se ao BrainTrade em 3 passos simples",
    "steps.0.title": "1. Inscreva-se e aprenda",
    "steps.0.text": "Inscreva-se hoje e tenha acesso imediato à nossa renomada academia de investimentos online.",
    "steps.1.title": "2. Coaching individual por telefone",
    "steps.1.text": "Após o cadastro, seu coach dedicado entrará em contato para uma sessão gratuita e explicará por que dominar o investimento online é essencial.",
    "steps.2.title": "3. Aprenda tudo sobre os mercados",
    "steps.2.text": "Comece sua jornada de aprendizado em trading online e obtenha insights sobre os mercados financeiros e as ferramentas necessárias para dominá-los."
   },
   "es": {
    "title": "Únete a BrainTrade en 3 pasos sencillos",
    "steps.0.title": "1. Regístrate y aprende",
    "steps.0.text": "Regístrate hoy y obtén acceso inmediato a nuestra reconocida academia de inversión en línea.",
    "steps.1.title": "2. Coaching telefónico uno a uno",
    "steps.1.text": "Después de registrarte, tu coach dedicado te llamará para una sesión gratuita y te explicará por qué dominar la inversión en línea es esencial.",
    "steps.2.title": "3. Aprende todo sobre los mercados",
    "steps.2.text": "Comienza tu recorrido educativo en trading en línea y obtén información sobre los mercados financieros y las herramientas que necesitas para dominarlos."
   },
   "ja": {
    "title": "BrainTradeに参加するための3つの簡単なステップ",
    "steps.0.title": "1. 無料登録して学ぶ",
    "steps.0.text": "今すぐ登録して、オンライン投資アカデミーにアクセスしましょう。",
    "steps.1.title": "2. 1対1の電話コーチング",
    "steps.1.text": "登録後、専任コーチからお電話し、無料セッションをご案内します。オンライン投資を学ぶ意義についてお伝えします。",
    "steps.2.title": "3. 市場のすべてを学ぶ",
    "steps.2.text": "オンライン取引の学びを始めましょう。金融市場と、そこで活用するツールへの理解を深められます。"
   },
   "vi": {
    "title": "Tham gia BrainTrade trong 3 bước đơn giản",
    "steps.0.title": "1. Đăng ký và học tập",
    "steps.0.text": "Đăng ký hôm nay để truy cập ngay vào học viện đầu tư trực tuyến hàng đầu của chúng tôi.",
    "steps.1.title": "2. Tư vấn 1-1 qua điện thoại",
    "steps.1.text": "Sau khi đăng ký, chuyên gia tư vấn riêng sẽ gọi điện cho bạn trong buổi tư vấn miễn phí, hướng dẫn cách bắt đầu hành trình đầu tư trực tuyến một cách hiệu quả.",
    "steps.2.title": "3. Khám phá toàn bộ thị trường",
    "steps.2.text": "Bắt đầu hành trình học giao dịch trực tuyến, khám phá các thị trường tài chính và làm chủ những công cụ cần thiết để thành công       "
   },
   "th": {
    "title": "เข้าร่วม BrainTrade ใน 3 ขั้นตอนง่ายๆ",
    "steps.0.title": "1. ลงทะเบียนและเรียนรู้",
    "steps.0.text": "ลงทะเบียนวันนี้ เข้าถึงแพลตฟอร์มเรียนรู้การลงทุนออนไลน์ระดับท็อปได้ทันที",
    "steps.1.title": "2. โค้ชตัวต่อตัวทางโทรศัพท์",
    "steps.1.text": "หลังจากลงทะเบียน โค้ชส่วนตัวจะโทรหาคุณในเซสชันฟรี เพื่อแนะนำว่าทำไมคุณถึงควรเชี่ยวชาญการลงทุนออนไลน์",
    "steps.2.title": "3. เรียนรู้ทุกตลาดการลงทุน",
    "steps.2.text": "เริ่มเรียนรู้การเทรดออนไลน์ พร้อมรับข้อมูลเชิงลึกของตลาดการเงิน และเครื่องมือที่จำเป็นต่อความสำเร็จของคุณ"
   },
   "it": {
    "title": "Unisciti a BrainTrade in 3 semplici passaggi",
    "steps.0.title": "1. Iscriviti e impara",
    "steps.0.text": "Registrati oggi e ottieni accesso immediato alla nostra apprezzata accademia di investimenti online.",
    "steps.1.title": "2. Coaching telefonico individuale",
    "steps.1.text": "Dopo la registrazione, il tuo coach dedicato ti chiamerà per una sessione gratuita per spiegarti perché è fondamentale padroneggiare gli investimenti online.",
    "steps.2.title": "3. Scopri tutto sui mercati",
    "steps.2.text": "Inizia il tuo percorso formativo nel trading online e scopri i mercati finanziari e gli strumenti necessari per padroneggiarli."
   },
   "fr": {
    "title": "Rejoignez BrainTrade en 3 étapes simples",
    "steps.0.title": "1. Inscrivez-vous et apprenez",
    "steps.0.text": "Inscrivez-vous aujourd'hui et accédez immédiatement à notre académie d'investissement en ligne très bien notée.",
    "steps.1.title": "2. Coaching téléphonique individuel",
    "steps.1.text": "Après votre inscription, votre coach dédié vous appellera pour une session gratuite afin d'expliquer pourquoi maîtriser l'investissement en ligne est essentiel.",
    "steps.2.title": "3. Découvrez tout sur les marchés",
    "steps.2.text": "Commencez votre parcours d'éducation au trading en ligne et obtenez des informations sur les marchés financiers et les outils dont vous avez besoin pour les conquérir."
   },
   "pl": {
    "title": "Dołącz do BrainTrade w 3 prostych krokach",
    "steps.0.title": "1. Zarejestruj się i ucz się",
    "steps.0.text": "Zarejestruj się już dziś i uzyskaj natychmiastowy dostęp do naszej renomowanej akademii inwestycyjnej online.",
    "steps.1.title": "2.  Indywidualny coaching telefoniczny",
    "steps.1.text": "Po rejestracji, Twój dedykowany coach zadzwoni do Ciebie na darmową sesję, aby wyjaśnić, dlaczego opanowanie inwestowania online jest kluczowe.",
    "steps.2.title": "3. Dowiedz się wszystkiego o rynkach",
    "steps.2.text": "Rozpocznij swoją naukę tradingu online i zdobądź wiedzę o rynkach finansowych oraz narzędziach, które pomogą Ci je opanować."
   },
   "sv": {
    "title": "Gå med i BrainTrade i 3 enkla steg",
    "steps.0.title": "1. Registrera dig och kom igång",
    "steps.0.text": "Registrera dig idag och få omedelbar tillgång till vår välrenommerade onlineinvesteringsakademi.",
    "steps.1.title": "2. Personlig telefoncoachning",
    "steps.1.text": "När du har registrerat dig ringer din personliga coach upp dig för ett kostnadsfritt samtal om varför det lönar sig att behärska onlineinvesteringar.",
    "steps.2.title": "3. Lär dig allt om marknaderna",
    "steps.2.text": "Börja din utbildning i onlinehandel och lär dig mer om de finansiella marknaderna och verktygen du behöver för att bemästra dem."
   }
  }
 },
 {
  "key": "bt-content-split",
  "name": "BT / Content (image + text)",
  "category": "braintrade",
  "position": 215,
  "html": "<section class=\"lp-sec-bt-content-split\">\n <div class=\"lp-wrap btcs-grid\">\n  <div class=\"btcs-copy\">\n   <h2 class=\"btcs-title\" data-lp-text=\"title\">Test Title</h2>\n   <p class=\"btcs-text\" data-lp-rich=\"text\">Rankos, Marita and Il Oji Nik, at Ed Olamkobner at Str. Condimentum at nonk in eros scelerisque ad. Commodo in viverra nonk, olamkorber aut. Non, amet, olect scelerisque notam sagittis, pulvinar.</p>\n  </div>\n  <div class=\"btcs-media\"><img data-lp-img=\"image\" src=\"\" alt=\"\"></div>\n </div>\n</section>",
  "css": ".lp-sec-bt-content-split{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-content-split .btcs-grid{display:grid;grid-template-columns:1fr 1fr;gap:44px;align-items:center}\n.lp-sec-bt-content-split .btcs-title{color:var(--lp-accent);font-size:1.7rem;font-weight:700;margin:0 0 14px}\n.lp-sec-bt-content-split .btcs-text{color:var(--lp-muted);line-height:1.7;margin:0;white-space:pre-line}\n.lp-sec-bt-content-split .btcs-media{border-radius:20px;background:#F8D8CC;min-height:300px;overflow:hidden}\n.lp-sec-bt-content-split .btcs-media img{width:100%;height:100%;object-fit:cover;display:block}\n@media (max-width:575px){.lp-sec-bt-content-split .btcs-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {}
  }
 },
 {
  "key": "bt-cards-grid",
  "name": "BT / Cards grid",
  "category": "braintrade",
  "position": 220,
  "html": "<section class=\"lp-sec-bt-cards-grid\">\n <div class=\"lp-wrap\">\n  <h2 class=\"btcg-title\" data-lp-text=\"title\">Lorem ipsum dolor sit amet, consectetur.</h2>\n  <div class=\"btcg-grid\">\n   <!--lp-repeat:cards--><div class=\"btcg-card\"><div class=\"btcg-media\"><img data-lp-img=\"image\" src=\"\" alt=\"\"></div><h3 class=\"btcg-card-title\" data-lp-text=\"title\">Title</h3><p class=\"btcg-card-text\" data-lp-rich=\"text\">Egestas elit dui scelerisque ut eu purus aliquam vitae habitasse.</p></div><!--/lp-repeat:cards-->\n  </div>\n </div>\n</section>",
  "css": ".lp-sec-bt-cards-grid{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-cards-grid .btcg-title{color:var(--lp-accent);font-size:1.9rem;font-weight:700;text-align:center;margin:0 0 34px}\n.lp-sec-bt-cards-grid .btcg-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:20px}\n.lp-sec-bt-cards-grid .btcg-card{background:#fff;border:1px solid #DDE1E6;border-radius:16px;padding:14px}\n.lp-sec-bt-cards-grid .btcg-media{border-radius:12px;background:#F8D8CC;height:150px;overflow:hidden;margin-bottom:12px}\n.lp-sec-bt-cards-grid .btcg-media img{width:100%;height:100%;object-fit:cover;display:block}\n.lp-sec-bt-cards-grid .btcg-card-title{color:var(--lp-accent);font-size:1rem;font-weight:600;margin:0 0 6px}\n.lp-sec-bt-cards-grid .btcg-card-text{color:var(--lp-muted);font-size:.88rem;line-height:1.5;margin:0}\n@media (max-width:1199px){.lp-sec-bt-cards-grid .btcg-grid{grid-template-columns:repeat(2,1fr)}}\n@media (max-width:575px){.lp-sec-bt-cards-grid .btcg-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {}
  }
 },
 {
  "key": "bt-cta",
  "name": "BT / CTA button",
  "category": "braintrade",
  "position": 225,
  "html": "<section class=\"lp-sec-bt-cta\">\n <div class=\"lp-wrap btc-inner\"><a class=\"btc-btn\" data-lp-link=\"cta_href\" data-lp-text=\"cta\" href=\"#signup\">Start Now</a></div>\n</section>",
  "css": ".lp-sec-bt-cta{background:var(--lp-bg);padding:26px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-cta .btc-inner{text-align:center}\n.lp-sec-bt-cta .btc-btn{display:inline-block;background:var(--lp-primary);color:#fff;border-radius:12px;padding:1rem 3rem;font-weight:700;font-size:1.05rem;text-decoration:none}",
  "texts": {
   "en": {}
  }
 },
 {
  "key": "bt-journey",
  "name": "BT / Journey (60 days)",
  "category": "braintrade",
  "position": 230,
  "html": "<section class=\"lp-sec-bt-journey\">\n <div class=\"lp-wrap\">\n  <h2 class=\"btj-title\" data-lp-text=\"title\">Your Guided Learning Journey in 60 Days</h2>\n  <div class=\"btj-grid\">\n   <!--lp-repeat:months--><div class=\"btj-card\"><span class=\"btj-label\" data-lp-text=\"label\">Month 1</span><h3 class=\"btj-card-title\" data-lp-text=\"title\">Learn &amp; Practice</h3><p class=\"btj-card-text\" data-lp-rich=\"text\">Build your foundation with structured educational guidance and ongoing feedback.</p></div><!--/lp-repeat:months-->\n  </div>\n </div>\n</section>",
  "css": ".lp-sec-bt-journey{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-journey .btj-title{color:var(--lp-accent);font-size:1.9rem;font-weight:700;text-align:center;margin:0 0 34px}\n.lp-sec-bt-journey .btj-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}\n.lp-sec-bt-journey .btj-card{background:#fff;border:1px solid #DDE1E6;border-radius:16px;padding:26px}\n.lp-sec-bt-journey .btj-label{display:inline-block;color:var(--lp-muted);border:1px solid #DDE1E6;border-radius:999px;padding:.25rem .8rem;font-size:.8rem;margin-bottom:12px}\n.lp-sec-bt-journey .btj-card-title{color:var(--lp-primary);font-size:1.25rem;font-weight:700;margin:0 0 10px}\n.lp-sec-bt-journey .btj-card-text{color:var(--lp-muted);line-height:1.6;margin:0}\n@media (max-width:575px){.lp-sec-bt-journey .btj-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {
    "title": "Your Guided Learning Journey in 60 Days",
    "months.0.label": "Month 1",
    "months.0.title": "Learn & Practice",
    "months.0.text": "Build your foundation with structured educational guidance and ongoing feedback, supporting the development of practical skills.  \nLearn within a guided framework that supports independent thinking and self-directed development.",
    "months.1.label": "Month 2",
    "months.1.title": "Grow with BrainTrade",
    "months.1.text": "Develop your knowledge and trade independently with educational assistance available. "
   },
   "pt": {
    "title": "Sua Jornada de Aprendizado Guiada em 60 Dias",
    "months.0.label": "Mês 1",
    "months.0.title": "Aprenda e Pratique",
    "months.0.text": "Construa uma base sólida com orientação estruturada e feedback contínuo para desenvolver suas habilidades práticas. Aprenda em um percurso guiado que estimula o pensamento independente e a autonomia.",
    "months.1.label": "Mês 2",
    "months.1.title": "Cresça com BrainTrade",
    "months.1.text": "Aprofunde seus conhecimentos e negocie por conta própria, com apoio educacional sempre disponível."
   },
   "it": {
    "title": "Il tuo percorso di apprendimento guidato in 60 giorni",
    "months.0.label": "Mese 1",
    "months.0.title": "Impara e pratica",
    "months.0.text": "Costruisci la tua base con una guida formativa strutturata e un feedback continuo, a sostegno dello sviluppo di competenze pratiche. Impara in un percorso guidato che favorisce il pensiero indipendente e l'apprendimento autonomo.",
    "months.1.label": "Mese 2",
    "months.1.title": "Cresci con BrainTrade",
    "months.1.text": "Sviluppa le tue conoscenze e fai trading in autonomia, con il supporto formativo sempre a disposizione."
   },
   "pl": {
    "title": "Twoja ścieżka nauki krok po kroku w 60 dni",
    "months.0.label": "Miesiąc 1",
    "months.0.title": "Ucz się i ćwicz",
    "months.0.text": "Zbuduj solidne podstawy dzięki uporządkowanemu wsparciu edukacyjnemu i ciągłej informacji zwrotnej, która wspiera rozwój praktycznych umiejętności. Ucz się w środowisku, które sprzyja niezależnemu myśleniu i samodzielnemu rozwojowi.",
    "months.1.label": "Miesiąc 2",
    "months.1.title": "Rozwijaj się z BrainTrade",
    "months.1.text": "Poszerzaj swoją wiedzę i zajmuj się tradingiem samodzielnie, ze stałym wsparciem edukacyjnym."
   },
   "sv": {
    "title": "Din guidade utbildningsresa på 60 dagar",
    "months.0.label": "Månad 1",
    "months.0.title": "Lär & Öva",
    "months.0.text": "Bygg din grund med strukturerad utbildning och kontinuerlig feedback som utvecklar dina praktiska färdigheter. Lär dig i en trygg miljö som främjar självständigt tänkande och egen utveckling.",
    "months.1.label": "Månad 2",
    "months.1.title": "Väx med BrainTrade",
    "months.1.text": "Utveckla din kunskap och handla på egen hand med utbildningsstöd när du behöver det."
   },
   "ja": {
    "title": "60日間の学習の道のり",
    "months.0.label": "1ヶ月目",
    "months.0.title": "学びと実践",
    "months.0.text": "体系的な指導と継続的なフィードバックで、実践的なスキルの土台を築きます。自分のペースで考え、行動できるよう、段階的なガイドのもとで学んでいきましょう。",
    "months.1.label": "2ヶ月目",
    "months.1.title": "BrainTradeと共に成長する",
    "months.1.text": "知識を深めながら、自分の取引を始めましょう。学んだ知識を実際の取引に活かし、プラットフォームの継続的なサポートを受けながら成長していきましょう。"
   },
   "th": {
    "title": "เส้นทางการเรียนรู้ใน 60 วัน",
    "months.0.label": "เดือนที่ 1",
    "months.0.title": "เรียนรู้และฝึกฝน",
    "months.0.text": "สร้างพื้นฐานที่แข็งแกร่งด้วยหลักสูตรการศึกษาที่ออกแบบมาอย่างเป็นระบบ ทดสอบทักษะของคุณในบัญชีทดลอง พร้อมรับการสนับสนุนจากที่ปรึกษาที่จะคอยให้คำแนะนำและพัฒนาความมั่นใจของคุณไปพร้อมกัน",
    "months.1.label": "เดือนที่ 2",
    "months.1.title": "เติบโตไปกับ BrainTrade",
    "months.1.text": "ต่อยอดความรู้และทักษะการเทรดได้ด้วยตัวคุณเอง พร้อมแหล่งเรียนรู้ที่ครบครัน ก้าวจากการฝึกฝนสู่การเทรดจริง โดยมีแพลตฟอร์มของเราคอยสนับสนุนคุณตลอดทาง"
   },
   "vi": {
    "title": "Hành trình học tập có hướng dẫn của bạn trong 60 ngày",
    "months.0.label": "Tháng 1",
    "months.0.title": "Học & Thực hành",
    "months.0.text": "Xây dựng nền tảng của bạn với sự hướng dẫn giáo dục có cấu trúc và phản hồi liên tục, hỗ trợ phát triển kỹ năng thực tiễn. Học trong một khuôn khổ được hướng dẫn giúp phát triển tư duy độc lập và khả năng tự định hướng.",
    "months.1.label": "Tháng 2",
    "months.1.title": "Phát triển cùng BrainTrade",
    "months.1.text": "Phát triển kiến thức của bạn và giao dịch độc lập với sự hỗ trợ giáo dục có sẵn. Chuyển từ tài nguyên học tập sang giao dịch tự định hướng với sự hỗ trợ liên tục từ BrainTrade."
   }
  }
 },
 {
  "key": "bt-benefits",
  "name": "BT / Benefits",
  "category": "braintrade",
  "position": 235,
  "html": "<section class=\"lp-sec-bt-benefits\">\n <div class=\"lp-wrap\">\n  <h2 class=\"btb-title\" data-lp-text=\"title\">Take your trading journey to the next level</h2>\n  <div class=\"btb-grid\">\n   <!--lp-repeat:cards--><div class=\"btb-card\"><div class=\"btb-icon\"><img data-lp-img=\"icon\" src=\"\" alt=\"\"></div><h3 class=\"btb-card-title\" data-lp-text=\"title\">Personal Trainer</h3><p class=\"btb-card-text\" data-lp-rich=\"text\">Receive 1-on-1 personalized guidance</p></div><!--/lp-repeat:cards-->\n  </div>\n </div>\n</section>",
  "css": ".lp-sec-bt-benefits{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-benefits .btb-title{color:var(--lp-accent);font-size:1.9rem;font-weight:700;text-align:center;margin:0 0 34px}\n.lp-sec-bt-benefits .btb-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}\n.lp-sec-bt-benefits .btb-card{background:#fff;border:1px solid #DDE1E6;border-radius:16px;padding:24px;text-align:center}\n.lp-sec-bt-benefits .btb-icon{height:88px;display:flex;align-items:center;justify-content:center;margin-bottom:12px}\n.lp-sec-bt-benefits .btb-icon img{max-height:88px;object-fit:contain}\n.lp-sec-bt-benefits .btb-card-title{color:var(--lp-accent);font-size:1.02rem;font-weight:600;margin:0 0 8px}\n.lp-sec-bt-benefits .btb-card-text{color:var(--lp-muted);font-size:.9rem;line-height:1.5;margin:0}\n@media (max-width:1199px){.lp-sec-bt-benefits .btb-grid{grid-template-columns:repeat(2,1fr)}}\n@media (max-width:575px){.lp-sec-bt-benefits .btb-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {
    "title": "Take your trading journey to the next level",
    "cards.0.title": "Personal Trainer",
    "cards.0.text": "Receive 1-on-1 personalized guidance",
    "cards.3.title": "Real-Time Market Signals",
    "cards.3.text": "Apply your learning in realistic conditions",
    "cards.1.title": "AI-Powered Trading Tools",
    "cards.1.text": "Enhance your decision-making while you learn",
    "cards.4.title": "Exclusive Content",
    "cards.4.text": "Access structured learning paths and advanced tutorials",
    "cards.2.title": "Live Campus",
    "cards.2.text": "Webinars, market updates, and live events",
    "cards.5.title": "Seamless Transition",
    "cards.5.text": "Move confidently from learning mode to practice mode"
   },
   "pt": {
    "title": "Leve sua jornada de trading para o próximo nível",
    "cards.0.title": "Coach Pessoal",
    "cards.0.text": "Receba orientação personalizada 1 a 1",
    "cards.3.title": "Sinais de Mercado em Tempo Real",
    "cards.3.text": "Aplique seu aprendizado em condições realistas",
    "cards.1.title": "Ferramentas de Trading com IA",
    "cards.1.text": "Tome decisões melhores à medida que aprende",
    "cards.4.title": "Conteúdo Exclusivo",
    "cards.4.text": "Acesse trilhas de aprendizado estruturadas e tutoriais avançados",
    "cards.2.title": "Live Campus",
    "cards.2.text": "Webinars, atualizações de mercado e eventos ao vivo",
    "cards.5.title": "Transição Suave",
    "cards.5.text": "Avance com confiança do modo de aprendizado para o modo de prática"
   },
   "it": {
    "title": "Porta il tuo percorso di trading al livello successivo",
    "cards.0.title": "Coach personale",
    "cards.0.text": "Ricevi formazione personalizzata e individuale",
    "cards.3.title": "Segnali di mercato in tempo reale",
    "cards.3.text": "Metti in pratica ciò che impari in condizioni realistiche",
    "cards.1.title": "Strumenti di trading potenziati dall'IA",
    "cards.1.text": "Migliora le tue decisioni mentre impari",
    "cards.4.title": "Contenuti esclusivi",
    "cards.4.text": "Accesso a percorsi di apprendimento strutturati e tutorial avanzati",
    "cards.2.title": "Campus Live",
    "cards.2.text": "Webinar, aggiornamenti di mercato ed eventi dal vivo",
    "cards.5.title": "Transizione senza soluzione di continuità",
    "cards.5.text": "Passa con sicurezza dalla modalità di apprendimento a quella di pratica"
   },
   "sv": {
    "title": "Ta din handel till nästa nivå",
    "cards.0.title": "Personlig mentor",
    "cards.0.text": "Få 1-mot-1-träning",
    "cards.3.title": "Marknadssignaler i realtid",
    "cards.3.text": "Tillämpa din kunskap under realistiska förhållanden",
    "cards.1.title": "AI-drivna handelsverktyg",
    "cards.1.text": "Fatta bättre beslut medan du lär dig",
    "cards.4.title": "Exklusivt innehåll",
    "cards.4.text": "Få tillgång till strukturerade utbildningsvägar och avancerade guider",
    "cards.2.title": "Live Campus",
    "cards.2.text": "Webinarier, marknadsuppdateringar och live-evenemang",
    "cards.5.title": "Smidig övergång",
    "cards.5.text": "Gå tryggt från utbildning till praktik"
   },
   "pl": {
    "title": "Przenieś swój trading na wyższy poziom",
    "cards.0.title": "Osobisty coach",
    "cards.0.text": "Otrzymaj spersonalizowane, indywidualne szkolenie",
    "cards.3.title": "Sygnaly rynkowe w czasie rzeczywistym",
    "cards.3.text": "Zastosuj swoją wiedzę w realistycznych warunkach",
    "cards.1.title": " Narzędzia tradingowe zasilane sztuczną inteligencją",
    "cards.1.text": "Zwiększ swoją zdolność podejmowania decyzji podczas nauki",
    "cards.4.title": "Ekskluzywne treści",
    "cards.4.text": "Dostęp do uporządkowanych ścieżek nauczania i zaawansowanych samouczków",
    "cards.2.title": "Campus Live ",
    "cards.2.text": "Webinaria, aktualizacje rynkowe i wydarzenia na żywo",
    "cards.5.title": "Bezproblemowe przejście",
    "cards.5.text": "Przechodź pewnie z trybu nauki do trybu praktyki"
   },
   "ja": {
    "title": "あなたのトレーディングの旅を次のレベルへ進めましょう",
    "cards.0.title": "パーソナルメンター",
    "cards.0.text": "専属メンターによる個別サポート",
    "cards.3.title": "リアルタイム市場シグナル",
    "cards.3.text": "現実的な条件で学びを応用する",
    "cards.1.title": "AI駆動のトレーディングツール",
    "cards.1.text": "学びながら意思決定を強化する",
    "cards.4.title": "限定コンテンツ",
    "cards.4.text": "段階的に学べるカリキュラムや応用チュートリアル",
    "cards.2.title": "ライブキャンパス",
    "cards.2.text": "ウェビナー、市場の最新情報、ライブイベント",
    "cards.5.title": "特典へのアクセス",
    "cards.5.text": "信頼できるブローカーの特別オファーを受け取る"
   },
   "vi": {
    "title": "Nâng cao hành trình giao dịch của bạn lên một tầm cao mới",
    "cards.0.title": "Cố vấn cá nhân",
    "cards.0.text": "Nhận hướng dẫn cá nhân hóa kèm riêng",
    "cards.3.title": "Tín hiệu thị trường theo thời gian thực",
    "cards.3.text": "Áp dụng kiến thức của bạn trong điều kiện thực tế",
    "cards.1.title": "Công cụ giao dịch sử dụng AI",
    "cards.1.text": "Cải thiện khả năng ra quyết định trong khi bạn học",
    "cards.4.title": "Nội dung độc quyền",
    "cards.4.text": "Truy cập các lộ trình học có cấu trúc và các hướng dẫn nâng cao",
    "cards.2.title": "Học trực tiếp cùng chuyên gia",
    "cards.2.text": "Hội thảo trực tuyến, cập nhật thị trường và sự kiện trực tiếp",
    "cards.5.title": "Quyền lợi dành riêng cho thành viên",
    "cards.5.text": "Nhận ưu đãi đặc biệt từ các nhà môi giới uy tín"
   },
   "th": {
    "title": "ยกระดับการเดินทางการเทรดของคุณ",
    "cards.0.title": "ผู้สอนส่วนตัว",
    "cards.0.text": "รับคำแนะนำตัวต่อตัวที่ปรับให้เหมาะกับคุณ",
    "cards.3.title": "สัญญาณตลาดแบบเรียลไทม์",
    "cards.3.text": "ความรู้เชิงลึกช่วยให้คุณเข้าใจสภาพตลาดที่กำลังเคลื่อนไหว",
    "cards.1.title": "เครื่องมือเทรดที่ขับเคลื่อนด้วย AI",
    "cards.1.text": "เพิ่มพูนการตัดสินใจของคุณในขณะที่เรียนรู้",
    "cards.4.title": "เนื้อหาพิเศษ",
    "cards.4.text": "เจาะลึกเนื้อหาการเรียนรู้ที่คัดสรรและเตรียมมาอย่างดี",
    "cards.2.title": " วิทยาเขตไลฟ์",
    "cards.2.text": "สัมมนาออนไลน์ ดีเบต และกิจกรรมสด",
    "cards.5.title": " โปรโมชั่นสุดพิเศษ",
    "cards.5.text": "รับข้อเสนอพิเศษจากโบรกเกอร์ที่เชื่อถือได้"
   }
  }
 },
 {
  "key": "bt-coaching",
  "name": "BT / Personal coaching",
  "category": "braintrade",
  "position": 240,
  "html": "<section class=\"lp-sec-bt-coaching\">\n <div class=\"lp-wrap btco-grid\">\n  <div class=\"btco-media\"><img data-lp-img=\"photo\" src=\"\" alt=\"\"></div>\n  <div class=\"btco-copy\">\n   <h2 class=\"btco-title\" data-lp-text=\"title\">Personal Coaching</h2>\n   <p class=\"btco-sub\" data-lp-text=\"subtitle\">Get professional 1-on-1 training</p>\n   <p class=\"btco-text\" data-lp-rich=\"body\">Our Academy Trainer program pairs you with a dedicated personal trading coach.</p>\n   <a class=\"btco-btn\" data-lp-link=\"cta_href\" data-lp-text=\"cta\" href=\"#signup\">Meet Your Trainer</a>\n  </div>\n </div>\n</section>",
  "css": ".lp-sec-bt-coaching{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-coaching .btco-grid{display:grid;grid-template-columns:1fr 1.2fr;gap:44px;align-items:center}\n.lp-sec-bt-coaching .btco-media{border-radius:20px;background:#F8D8CC;min-height:320px;overflow:hidden}\n.lp-sec-bt-coaching .btco-media img{width:100%;height:100%;object-fit:cover;display:block}\n.lp-sec-bt-coaching .btco-title{color:var(--lp-primary);font-size:1.7rem;font-weight:700;margin:0 0 6px}\n.lp-sec-bt-coaching .btco-sub{color:var(--lp-accent);font-weight:600;font-size:1.05rem;margin:0 0 14px}\n.lp-sec-bt-coaching .btco-text{color:var(--lp-muted);line-height:1.7;margin:0 0 22px;white-space:pre-line}\n.lp-sec-bt-coaching .btco-btn{display:inline-block;background:var(--lp-primary);color:#fff;border-radius:12px;padding:.95rem 2.4rem;font-weight:700;text-decoration:none}\n@media (max-width:575px){.lp-sec-bt-coaching .btco-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {
    "title": "Personal Coaching",
    "subtitle": "Get professional 1-on-1 training",
    "body": "Our Academy Trainer program pairs you with a dedicated personal trading coach who knows your goals and stays with you every step of the way. Get real-time answers by phone, practical training on live market setups, and steady support to build sharp trading skills with confidence.",
    "cta": "Meet Your Trainer"
   },
   "pt": {
    "title": "Mentoria Pessoal",
    "subtitle": "Receba orientação profissional 1 a 1",
    "body": "O programa de mentoria da nossa Academia conecta você a um coach pessoal de trading que conhece seus objetivos e está com você em cada etapa da jornada. Tenha respostas em tempo real por telefone, treinamento prático com setups de mercado ao vivo e suporte constante para desenvolver suas habilidades de trading com confiança.",
    "cta": "Quero conhecer meu mentor"
   },
   "ja": {
    "title": "パーソナルコーチング",
    "subtitle": "専任メンターが1対1で学びをサポート",
    "body": "私たちのアカデミートレーナープログラムでは、あなたの目標を理解し、常にサポートしてくれる専任のパーソナルトレーディングコーチとペアを組みます。電話でのリアルタイムの回答、ライブマーケットセットアップに関する実践的なトレーニング、そして自信を持って鋭いトレーディングスキルを身につけるための安定したサポートを受けることができます。",
    "cta": "メンターと学び始める"
   },
   "th": {
    "title": "โค้ชส่วนตัว",
    "subtitle": "รับคำแนะนำแบบ 1 ต่อ 1 จากมืออาชีพ",
    "body": "โปรแกรมที่ปรึกษาของเราเชื่อมโยงคุณกับโค้ชที่จะเข้าใจเป้าหมายของคุณและอยู่เคียงข้างคุณในทุกขั้นตอน รับคำตอบแบบเรียลไทม์ทางโทรศัพท์ คำแนะนำที่เป็นประโยชน์เกี่ยวกับการตั้งค่าตลาดสด และการสนับสนุนอย่างต่อเนื่องเพื่อสร้างทักษะการซื้อขายที่เฉียบคมด้วยความมั่นใจ",
    "cta": "นัดพบที่ปรึกษาของคุณ"
   },
   "vi": {
    "title": "Huấn luyện cá nhân",
    "subtitle": "Nhận hướng dẫn chuyên nghiệp 1-kèm-1",
    "body": "Chương trình huấn luyện viên của chúng tôi kết nối bạn với một huấn luyện viên giao dịch cá nhân tận tâm, người hiểu rõ mục tiêu của bạn và đồng hành cùng bạn trong từng bước. Nhận câu trả lời ngay lập tức qua điện thoại, đào tạo thực tế trên các tình huống thị trường thực, và hỗ trợ liên tục để tự tin xây dựng kỹ năng giao dịch sắc bén.",
    "cta": "Gặp gỡ Huấn luyện viên của bạn"
   },
   "it": {
    "title": "Coaching Personale",
    "subtitle": "Ricevi formazione professionale individuale",
    "body": "Il nostro programma Academy Trainer ti abbina a un coach personale dedicato al trading che conosce i tuoi obiettivi e ti accompagna in ogni fase del percorso. Ricevi risposte in tempo reale al telefono, formazione pratica sui setup di mercato dal vivo e supporto costante per affinare le tue capacità di trading e operare con sicurezza.",
    "cta": "Voglio conoscere il mio mentore"
   },
   "pl": {
    "title": "Coaching osobisty",
    "subtitle": "Uzyskaj profesjonalne szkolenie indywidualne",
    "body": "Nasz program Academy Trainer łączy Cię z dedykowanym, osobistym coachem tradingowym, który zna Twoje cele i towarzyszy Ci na każdym kroku. Uzyskaj odpowiedzi w czasie rzeczywistym przez telefon, praktyczne szkolenie na żywych przykładach rynkowych oraz stałe wsparcie, aby pewnie rozwijać umiejętności tradingowe.",
    "cta": " Chcę poznać swojego coacha"
   },
   "sv": {
    "title": "Personlig coaching",
    "subtitle": "Få professionell 1-mot-1-träning",
    "body": "Vårt Academy Trainer-program matchar dig med en personlig handelscoach som känner till dina mål och stöttar dig hela vägen. Få svar i realtid via telefon, praktisk träning i riktiga marknadsscenarier och kontinuerligt stöd för att bygga upp dina handelsfärdigheter och ditt självförtroende.",
    "cta": "Möt din mentor"
   }
  }
 },
 {
  "key": "bt-learn",
  "name": "BT / Learn & practice",
  "category": "braintrade",
  "position": 245,
  "html": "<section class=\"lp-sec-bt-learn\">\n <div class=\"lp-wrap btl-grid\">\n  <div class=\"btl-copy\">\n   <h2 class=\"btl-title\" data-lp-text=\"title\">Learn and Practice</h2>\n   <p class=\"btl-sub\" data-lp-text=\"subtitle\">Join our Live Campus</p>\n   <p class=\"btl-text\" data-lp-rich=\"body\">All your courses, trainer sessions, and trading tools — accessible in one platform.</p>\n   <div class=\"btl-bullets\">\n    <!--lp-repeat:bullets--><p class=\"btl-bullet\" data-lp-text=\"label\">✓ Let us introduce you to the Financial Markets</p><!--/lp-repeat:bullets-->\n   </div>\n  </div>\n  <div class=\"btl-media\"><img data-lp-img=\"screenshot\" src=\"\" alt=\"\"></div>\n </div>\n</section>",
  "css": ".lp-sec-bt-learn{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-learn .btl-grid{display:grid;grid-template-columns:1.1fr 1fr;gap:44px;align-items:center}\n.lp-sec-bt-learn .btl-title{color:var(--lp-accent);font-size:1.7rem;font-weight:700;margin:0 0 6px}\n.lp-sec-bt-learn .btl-sub{color:var(--lp-primary);font-weight:600;font-size:1.05rem;margin:0 0 14px}\n.lp-sec-bt-learn .btl-text{color:var(--lp-muted);line-height:1.7;margin:0 0 18px;white-space:pre-line}\n.lp-sec-bt-learn .btl-bullet{color:var(--lp-accent);margin:.45rem 0;font-size:.95rem}\n.lp-sec-bt-learn .btl-media{border-radius:16px;overflow:hidden;background:#F8D8CC;min-height:260px}\n.lp-sec-bt-learn .btl-media img{width:100%;height:100%;object-fit:cover;display:block}\n@media (max-width:575px){.lp-sec-bt-learn .btl-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {
    "title": "Learn and Practice",
    "subtitle": "Join our Live Campus",
    "body": "All your courses, trainer sessions, and trading tools - accessible in one platform. Whether it’s trading basics, digital asset fundamentals or an introduction to Technical Analysis, we got you covered. You just sit back and watch! ",
    "bullets.0.label": "Let us introduce you to the Financial Markets",
    "bullets.1.label": "Watch our exclusive videos on hot trading topics",
    "bullets.2.label": "Find out all about Digital Assets",
    "bullets.3.label": "Learn How to use Technical Analysis",
    "bullets.4.label": "Take advantage of our AI-Powered Trading Tools"
   },
   "pt": {
    "title": "Aprenda, Pratique e Negocie",
    "subtitle": "Junte-se ao nosso Live Campus",
    "body": "Todos os cursos, sessões de treinamento e ferramentas de negociação — acessíveis em uma única plataforma. Do básico da negociação aos fundamentos de ativos digitais e à introdução à análise técnica, temos tudo o que você precisa. É só relaxar e assistir!",
    "bullets.0.label": "Conheça os mercados financeiros",
    "bullets.1.label": "Assista aos nossos vídeos exclusivos sobre os principais tópicos de negociação",
    "bullets.2.label": "Descubra tudo sobre ativos digitais",
    "bullets.3.label": "Aprenda a usar a análise técnica",
    "bullets.4.label": "Aproveite nossas ferramentas de negociação com inteligência artificial"
   },
   "ja": {
    "title": "学ぶ、練習する、そして取引する",
    "subtitle": "ライブキャンパスに参加する",
    "body": "すべてのコース、トレーナーセッション、トレーディングツールが1つのプラットフォームで利用可能です。トレーディングの基本、デジタル資産の基礎、またはテクニカル分析の入門など、私たちがサポートします。あなたはただリラックスして見ているだけで大丈夫です！",
    "bullets.0.label": "金融市場の基礎をわかりやすく紹介",
    "bullets.1.label": "注目のトレーディングテーマを扱う限定ビデオを視聴可能",
    "bullets.2.label": "デジタル資産を体系的に理解",
    "bullets.3.label": "テクニカル分析の基礎を学習",
    "bullets.4.label": "AI駆動のトレーディングツールを活用"
   },
   "th": {
    "title": " เรียนรู้ ฝึกฝน และเทรด",
    "subtitle": "เข้าร่วมแคมปัสไลฟ์ของเรา",
    "body": "หลักสูตรทั้งหมด เซสชันให้คำปรึกษา และเครื่องมือการเทรด — ครบในแพลตฟอร์มเดียว ตั้งแต่พื้นฐานการเทรด ความรู้เรื่องสินทรัพย์ดิจิทัล ไปจนถึงการวิเคราะห์ทางเทคนิค เราเตรียมไว้ให้คุณครบ คุณแค่นั่งลงและเริ่มเรียนรู้ได้เลย",
    "bullets.0.label": "ให้เราพาคุณก้าวเข้าสู่ตลาดการเงิน",
    "bullets.1.label": "ดูวิดีโอพิเศษเกี่ยวกับหัวข้อการเทรดที่กำลังมาแรง",
    "bullets.2.label": "เรียนรู้ทุกเรื่องเกี่ยวกับสินทรัพย์ดิจิทัล",
    "bullets.3.label": "เรียนรู้วิธีใช้การวิเคราะห์ทางเทคนิค",
    "bullets.4.label": "ใช้ประโยชน์จากเครื่องมือเทรดที่ขับเคลื่อนด้วย AI ของเรา"
   },
   "vi": {
    "title": "Học, Thực hành và Giao dịch",
    "subtitle": "Tham gia Học trực tiếp cùng chuyên gia của chúng tôi",
    "body": "Tất cả các khóa học, buổi huấn luyện và công cụ giao dịch của bạn — đều có sẵn trên một nền tảng. Dù là kiến thức cơ bản về giao dịch, các nguyên tắc về tài sản kỹ thuật số hay giới thiệu về Phân tích Kỹ thuật, chúng tôi đều có thể hỗ trợ bạn. Bạn chỉ cần ngồi lại và theo dõi!",
    "bullets.0.label": "Hãy để chúng tôi giới thiệu cho bạn về Thị trường Tài chính",
    "bullets.1.label": "Xem các video độc quyền của chúng tôi về các chủ đề giao dịch nóng",
    "bullets.2.label": "Tìm hiểu tất cả về Tài sản Kỹ thuật Số",
    "bullets.3.label": "Học cách sử dụng Phân tích Kỹ thuật",
    "bullets.4.label": "Tận dụng các Công cụ Giao dịch AI của chúng tôi"
   },
   "it": {
    "title": "Impara e Pratica",
    "subtitle": "Unisciti al nostro Campus Live",
    "body": "Tutti i tuoi corsi, sessioni di formazione e strumenti di trading - accessibili su un'unica piattaforma. Che si tratti di nozioni di base sul trading, fondamenti degli asset digitali o un'introduzione all'analisi tecnica, abbiamo tutto ciò di cui hai bisogno. Tu ti siedi e guardi!",
    "bullets.0.label": "Conosci i mercati finanziari",
    "bullets.1.label": "Guarda i nostri video esclusivi sui temi di trading del momento",
    "bullets.2.label": "Scopri tutto sugli asset digitali",
    "bullets.3.label": "Impara a utilizzare l'analisi tecnica",
    "bullets.4.label": "Sfrutta i nostri strumenti di trading potenziati dall'IA"
   },
   "pl": {
    "title": "Ucz się i ćwicz",
    "subtitle": "Dołącz do naszego Campus Live",
    "body": "Wszystkie kursy, sesje coachingowe i narzędzia tradingowe – dostępne na jednej platformie. Niezależnie od tego, czy chodzi o podstawy tradingu, fundamenty aktywów cyfrowych, czy wprowadzenie do analizy technicznej — mamy wszystko, czego potrzebujesz. Wystarczy usiąść i oglądać!",
    "bullets.0.label": "Poznaj rynki finansowe",
    "bullets.1.label": "Obejrzyj nasze ekskluzywne filmy o najważniejszych tematach w tradingu",
    "bullets.2.label": "Dowiedz się wszystkiego o aktywach cyfrowych",
    "bullets.3.label": "Naucz się, jak korzystać z analizy technicznej",
    "bullets.4.label": "Skorzystaj z naszych narzędzi tradingowych zasilanych sztuczną inteligencją"
   },
   "sv": {
    "title": "Lär dig och öva",
    "subtitle": "Gå med i vårt Live Campus",
    "body": "Alla dina kurser, övningssessioner och handelsverktyg – tillgängliga på en plattform. Oavsett om det handlar om grunderna i handel, grunderna i digitala tillgångar eller en introduktion till teknisk analys, så har vi det du behöver. Du behöver bara luta dig tillbaka och följa med.",
    "bullets.0.label": "Vi introducerar dig till de finansiella marknaderna",
    "bullets.1.label": "Titta på våra exklusiva videor om aktuella handelsämnen",
    "bullets.2.label": "Ta reda på allt om digitala tillgångar",
    "bullets.3.label": "Lär dig att använda teknisk analys",
    "bullets.4.label": "Dra nytta av våra AI-drivna handelsverktyg"
   }
  }
 },
 {
  "key": "bt-switch",
  "name": "BT / Switch to trader mode",
  "category": "braintrade",
  "position": 250,
  "html": "<section class=\"lp-sec-bt-switch\">\n <div class=\"lp-wrap btsw-grid\">\n  <div class=\"btsw-media\"><img data-lp-img=\"screenshot\" src=\"\" alt=\"\"></div>\n  <div class=\"btsw-copy\">\n   <h2 class=\"btsw-title\" data-lp-text=\"title\">Switch To Trader Mode</h2>\n   <p class=\"btsw-sub\" data-lp-text=\"subtitle\">Get ready to enter the world of trading</p>\n   <p class=\"btsw-text\" data-lp-rich=\"body\">Access educational resources, practice in a simulated environment, and trade independently when you choose.</p>\n  </div>\n </div>\n</section>",
  "css": ".lp-sec-bt-switch{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-switch .btsw-grid{display:grid;grid-template-columns:1fr 1.1fr;gap:44px;align-items:center}\n.lp-sec-bt-switch .btsw-media{border-radius:16px;overflow:hidden;background:#F8D8CC;min-height:260px}\n.lp-sec-bt-switch .btsw-media img{width:100%;height:100%;object-fit:cover;display:block}\n.lp-sec-bt-switch .btsw-title{color:var(--lp-accent);font-size:1.7rem;font-weight:700;margin:0 0 6px}\n.lp-sec-bt-switch .btsw-sub{color:var(--lp-primary);font-weight:600;font-size:1.05rem;margin:0 0 14px}\n.lp-sec-bt-switch .btsw-text{color:var(--lp-muted);line-height:1.7;margin:0;white-space:pre-line}\n@media (max-width:575px){.lp-sec-bt-switch .btsw-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {
    "title": "Switch To Trader Mode",
    "subtitle": "Get ready to enter the world of trading",
    "body": "Access educational resources, practice in a simulated environment, and trade independently when you choose!"
   },
   "pt": {
    "title": "Mude para o Modo Trader",
    "subtitle": "Conecte sua conta a corretoras confiáveis",
    "body": "Acesse recursos educacionais, pratique em um ambiente simulado e negocie por conta própria quando quiser!"
   },
   "ja": {
    "title": "トレーダーモードに切り替える",
    "subtitle": "信頼できるブローカーとアカウントを連携",
    "body": "教育リソースにアクセスし、シミュレーション環境で練習し、あなたが選んだときに独立して取引しましょう！"
   },
   "th": {
    "title": "จากนักเรียน...สู่เทรดเดอร์",
    "subtitle": " เชื่อมต่อบัญชีของคุณกับโบรกเกอร์ที่เชื่อถือได้",
    "body": "ก้าวออกจากบัญชีทดลอง สู่การเทรดจริงได้อย่างไร้รอยต่อ เชื่อม BrainTrade เข้ากับโบรกเกอร์ของคุณด้วยรหัสยืนยัน แล้วเทรดได้จากแพลตฟอร์มเดียว — เรียนรู้ ฝึกฝน เทรดจริง ครบจบในที่เดียว"
   },
   "vi": {
    "title": "Chuyển sang Chế độ Giao dịch",
    "subtitle": "Kết nối tài khoản của bạn với các Nhà môi giới uy tín",
    "body": "Truy cập tài nguyên giáo dục, thực hành trong môi trường mô phỏng và giao dịch độc lập khi bạn muốn!"
   },
   "it": {
    "title": "Passa alla modalità Trader",
    "subtitle": "Preparati a entrare nel mondo del trading",
    "body": "Accedi a risorse formative, esercitati in un ambiente simulato e fai trading in autonomia quando vuoi!"
   },
   "pl": {
    "title": "Przełącz na tryb tradera",
    "subtitle": "Przygotuj się na wejście w świat tradingu",
    "body": "Uzyskaj dostęp do zasobów edukacyjnych, ćwicz w symulowanym środowisku i samodzielnie zajmuj się tradingiem, kiedy chcesz!"
   },
   "sv": {
    "title": "Aktivera Trader-läget",
    "subtitle": "Ta steget in i handelns värld",
    "body": "Få tillgång till utbildningsmaterial, öva i en simulerad miljö och handla på egen hand när du vill."
   },
   "es": {
    "title": "Cambia al Modo Trader",
    "subtitle": "Prepárate para entrar al mundo del trading",
    "body": "Accede a recursos educativos, practica en un entorno simulado y opera por tu cuenta cuando quieras."
   }
  }
 },
 {
  "key": "bt-faq",
  "name": "BT / FAQ",
  "category": "braintrade",
  "position": 255,
  "html": "<section class=\"lp-sec-bt-faq\">\n <div class=\"lp-wrap btf-grid\">\n  <div class=\"btf-left\">\n   <h2 class=\"btf-title\" data-lp-text=\"title\">Frequently Asked Questions</h2>\n   <p class=\"btf-sub\" data-lp-rich=\"subtitle\">We are glad to help! Here are some of the most common questions.</p>\n   <div class=\"btf-media\"><img data-lp-img=\"photo\" src=\"\" alt=\"\"></div>\n  </div>\n  <div class=\"btf-list\">\n   <!--lp-repeat:faq--><div class=\"btf-item\" data-lp-acc><button class=\"faq-q\" type=\"button\"><span data-lp-text=\"q\">Do I need prior experience to start the courses?</span><span class=\"btf-x\">+</span></button><div class=\"faq-a btf-a\"><p data-lp-rich=\"a\">No prior experience is required to start the courses.</p></div></div><!--/lp-repeat:faq-->\n  </div>\n </div>\n</section>",
  "css": ".lp-sec-bt-faq{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-faq .btf-grid{display:grid;grid-template-columns:1fr 1.25fr;gap:44px;align-items:start}\n.lp-sec-bt-faq .btf-title{color:var(--lp-accent);font-size:1.7rem;font-weight:700;margin:0 0 10px}\n.lp-sec-bt-faq .btf-sub{color:var(--lp-muted);line-height:1.6;margin:0 0 20px}\n.lp-sec-bt-faq .btf-media{border-radius:16px;overflow:hidden;background:#F8D8CC;min-height:220px}\n.lp-sec-bt-faq .btf-media img{width:100%;height:100%;object-fit:cover;display:block}\n.lp-sec-bt-faq .btf-item{background:#fff;border:1px solid #DDE1E6;border-radius:12px;margin-bottom:12px;overflow:hidden}\n.lp-sec-bt-faq .btf-item.open{border-color:var(--lp-primary)}\n.lp-sec-bt-faq .faq-q{width:100%;display:flex;justify-content:space-between;align-items:center;gap:14px;background:none;border:0;padding:16px 18px;font:inherit;font-weight:600;color:var(--lp-accent);cursor:pointer;text-align:left}\n.lp-sec-bt-faq .btf-x{color:var(--lp-primary);font-size:1.35rem;line-height:1;transition:transform .2s ease}\n.lp-sec-bt-faq .btf-item.open .btf-x{transform:rotate(45deg)}\n.lp-sec-bt-faq .btf-a{display:none;padding:0 18px 16px;color:var(--lp-muted);line-height:1.6}\n.lp-sec-bt-faq .btf-item.open .btf-a{display:block}\n.lp-sec-bt-faq .btf-a p{margin:0}\n@media (max-width:575px){.lp-sec-bt-faq .btf-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {
    "title": "Frequently Asked Questions",
    "subtitle": "We are glad to help! Here are some of the most common questions and queries about BrainTrade, to save you some time.",
    "faq.0.q": "Do I need prior experience to start the courses?",
    "faq.0.a": "No prior experience is required to start the courses. BrainTrade values transparency above all else, and our goal is to guide you through the educational process step by step, starting from the fundamentals. ",
    "faq.1.q": "Why should I upgrade my package with BrainTrade?",
    "faq.1.a": "…",
    "faq.2.q": "Is BrainTrade safe? ",
    "faq.2.a": "Yes. BrainTrade (www.thebraintrade.com) is a licensed platform operated by BT Nexus Limited. The Group includes Intraservice Ltd, a limited liability company incorporated under the laws of the Republic of Cyprus, with registered address Arch. Makariou III, 73, METHONIS TOWER, 3rd Floor, Flat/Office 301A, 1070, Nicosia, Cyprus. Intraservice Ltd provides intra-group payment services for and on behalf of BT Nexus Limited.",
    "faq.3.q": "How can I ask other questions about BrainTrade?",
    "faq.3.a": "…",
    "faq.4.q": "Is BrainTrade only about trading courses?",
    "faq.4.a": "…",
    "faq.5.q": "How is BrainTrade different from buying a random trading course?",
    "faq.5.a": "…"
   },
   "pt": {
    "title": "Perguntas Frequentes",
    "subtitle": "Estamos aqui para ajudar! Confira abaixo as perguntas mais frequentes sobre o BrainTrade — para você não perder tempo.",
    "faq.0.q": "Preciso de experiência prévia para começar os cursos?",
    "faq.0.a": "…",
    "faq.1.q": "Não é necessária experiência prévia para iniciar os cursos. O BrainTrade preza pela transparência, e nosso objetivo é guiar você por todo o processo educativo, passo a passo — começando pelos fundamentos.",
    "faq.1.a": "…",
    "faq.2.q": "Por que fazer upgrade do meu plano no BrainTrade?",
    "faq.2.a": "Sim. O BrainTrade (www.thebraintrade.com) é uma plataforma licenciada, operada pela BT Nexus Limited. O Grupo inclui a Intraservice Ltd, uma sociedade de responsabilidade limitada, constituída e existente de acordo com as leis da República do Chipre, com sede registrada em Arch. Makariou III, 73, METHONIS TOWER, 3º andar, Sala/Escritório 301A, 1070, Nicósia, Chipre. A Intraservice Ltd presta serviços de pagamento intragrupo para e em nome da BT Nexus Limited.",
    "faq.3.q": "Como posso fazer outras perguntas sobre o BrainTrade?",
    "faq.3.a": "…",
    "faq.4.q": "O BrainTrade oferece apenas cursos de trading?",
    "faq.4.a": "…",
    "faq.5.q": "Qual a diferença entre o BrainTrade e um curso de trading qualquer?",
    "faq.5.a": "…"
   },
   "it": {
    "title": "Domande frequenti",
    "subtitle": "Siamo felici di aiutarti! Ecco alcune delle domande più frequenti su BrainTrade, per farti risparmiare tempo.",
    "faq.0.q": "Ho bisogno di esperienza precedente per iniziare i corsi?",
    "faq.0.a": "…",
    "faq.1.q": "Non è necessaria alcuna esperienza per iniziare i corsi. BrainTrade tiene alla trasparenza più di ogni altra cosa e il nostro obiettivo è guidarti passo dopo passo nel percorso formativo, partendo dalle basi.",
    "faq.1.a": "…",
    "faq.2.q": "Perché dovrei passare a un pacchetto superiore con BrainTrade?",
    "faq.2.a": "Sì. BrainTrade (www.thebraintrade.com) è una piattaforma autorizzata gestita da BT Nexus Limited. Il Gruppo include Intraservice Ltd, una società a responsabilità limitata costituita ed esistente ai sensi delle leggi della Repubblica di Cipro, con sede legale in Arch. Makariou III, 73, METHONIS TOWER, 3° piano, Appartamento/Ufficio 301A, 1070, Nicosia, Cipro. Intraservice Ltd fornisce servizi di pagamento infragruppo per e per conto di BT Nexus Limited.",
    "faq.3.q": "Come posso porre altre domande su BrainTrade?",
    "faq.3.a": "…",
    "faq.4.q": " BrainTrade riguarda solo i corsi di trading?",
    "faq.4.a": "…",
    "faq.5.q": "In che modo BrainTrade è diverso dall'acquisto di un corso di trading qualsiasi?",
    "faq.5.a": "…"
   },
   "pl": {
    "title": "Najczęściej zadawane pytania",
    "subtitle": "Cieszymy się, że możemy pomóc! Oto niektóre z najczęściej zadawanych pytań dotyczących BrainTrade, aby zaoszczędzić Ci czas.",
    "faq.0.q": "Czy potrzebuję wcześniejszego doświadczenia, aby rozpocząć kursy?",
    "faq.0.a": "…",
    "faq.1.q": "Nie jest wymagane wcześniejsze doświadczenie, aby rozpocząć kursy. BrainTrade ceni przejrzystość ponad wszystko, a naszym celem jest prowadzenie Cię przez proces edukacyjny krok po kroku, zaczynając od podstaw.",
    "faq.1.a": "…",
    "faq.2.q": "Dlaczego warto przejść na wyższy pakiet BrainTrade?",
    "faq.2.a": "Tak. BrainTrade (www.thebraintrade.com) to licencjonowana platforma prowadzona przez BT Nexus Limited. Grupa obejmuje Intraservice Ltd, spółkę z ograniczoną odpowiedzialnością utworzoną i działającą zgodnie z prawem Republiki Cypru, z siedzibą pod adresem: Arch. Makariou III, 73, METHONIS TOWER, 3. piętro, lokal/mieszkanie 301A, 1070, Nikozja, Cypr. Intraservice Ltd świadczy wewnątrzgrupowe usługi płatnicze dla i w imieniu BT Nexus Limited.",
    "faq.3.q": "Jak mogę zadać inne pytania dotyczące BrainTrade?",
    "faq.3.a": "…",
    "faq.4.q": " Czy BrainTrade dotyczy tylko kursów tradingowych?",
    "faq.4.a": "…",
    "faq.5.q": "Czym BrainTrade różni się od zakupu przypadkowego kursu tradingowego?",
    "faq.5.a": "…"
   },
   "sv": {
    "title": "Vanliga frågor",
    "subtitle": "Vi hjälper gärna till. Här är de vanligaste frågorna och funderingarna om BrainTrade – så sparar du tid.",
    "faq.0.q": "Behöver jag tidigare erfarenhet för att gå kurserna?",
    "faq.0.a": "Ingen tidigare erfarenhet krävs. På BrainTrade sätter vi transparens främst och vårt mål är att vägleda dig genom hela utbildningen steg för steg – från grunden.",
    "faq.1.q": "Varför ska jag uppgradera mitt paket med BrainTrade?",
    "faq.1.a": "…",
    "faq.2.q": "Vilka betalningsmetoder kan jag använda?",
    "faq.2.a": "Ja. BrainTrade (www.thebraintrade.com) är en licensierad plattform som drivs av BT Nexus Limited. Koncernen inkluderar Intraservice Ltd, ett aktiebolag med begränsat ansvar, bildat och verksamt enligt lagarna i Republiken Cypern, med registrerad adress Arch. Makariou III, 73, METHONIS TOWER, 3:e våningen, lägenhet/kontor 301A, 1070, Nicosia, Cypern. Intraservice Ltd tillhandahåller interna koncernbetalningstjänster för och på uppdrag av BT Nexus Limited.",
    "faq.3.q": "Hur kan jag få svar på fler frågor om BrainTrade?",
    "faq.3.a": "…",
    "faq.4.q": "Erbjuder BrainTrade endast handelskurser?",
    "faq.4.a": "…",
    "faq.5.q": "Hur skiljer sig BrainTrade från vilken annan handelskurs som helst?",
    "faq.5.a": "…"
   },
   "fr": {
    "title": "Questions Fréquemment Posées",
    "subtitle": "Nous sommes heureux de vous aider ! Voici quelques-unes des questions et demandes les plus courantes concernant BrainTrade, pour vous faire gagner du temps.",
    "faq.0.q": "Ai-je besoin d'une expérience préalable pour commencer les cours ?",
    "faq.0.a": "Aucune expérience préalable n'est requise pour commencer les cours. BrainTrade valorise la transparence avant tout, et notre objectif est de vous guider à travers le processus éducatif étape par étape, en commençant par les fondamentaux.",
    "faq.1.q": "Pourquoi devrais-je mettre à niveau mon forfait avec BrainTrade ?",
    "faq.1.a": "…",
    "faq.2.q": "BrainTrade est-il sûr ?",
    "faq.2.a": "Oui. BrainTrade (www.thebraintrade.com) est une plateforme agréée exploitée par BT Nexus Limited. Le Groupe comprend Intraservice Ltd, une société à responsabilité limitée constituée et existant selon les lois de la République de Chypre, dont l’adresse enregistrée est Arch. Makariou III, 73, METHONIS TOWER, 3e étage, Appartement/Bureau 301A, 1070, Nicosie, Chypre. Intraservice Ltd fournit des services de paiement intragroupe pour et au nom de BT Nexus Limited.",
    "faq.3.q": "Comment puis-je poser d'autres questions sur BrainTrade ?",
    "faq.3.a": "…",
    "faq.4.q": "BrainTrade ne concerne-t-il que les cours de trading ?",
    "faq.4.a": "…",
    "faq.5.q": "En quoi BrainTrade est-il différent de l'achat d'un cours de trading aléatoire ?",
    "faq.5.a": "…"
   },
   "de": {
    "title": "Häufig gestellte Fragen",
    "subtitle": "Wir helfen Ihnen gerne! Hier sind einige der häufigsten Fragen und Anfragen zu BrainTrade, um Ihnen Zeit zu sparen.",
    "faq.0.q": "Brauche ich Vorerfahrung, um die Kurse zu beginnen?",
    "faq.0.a": "Für den Beginn der Kurse sind keine Vorkenntnisse erforderlich. BrainTrade legt größten Wert auf Transparenz und unser Ziel ist es, Sie Schritt für Schritt durch den Bildungsprozess zu führen, beginnend mit den Grundlagen.",
    "faq.1.q": "Warum sollte ich mein Paket bei BrainTrade upgraden?",
    "faq.1.a": "…",
    "faq.2.q": "Ist BrainTrade sicher?",
    "faq.2.a": "Ja. BrainTrade (www.thebraintrade.com) ist eine lizenzierte Plattform, die von BT Nexus Limited betrieben wird. Zur Gruppe gehört Intraservice Ltd, eine Gesellschaft mit beschränkter Haftung, die nach dem Recht der Republik Zypern gegründet wurde und besteht, mit eingetragener Anschrift Arch. Makariou III, 73, METHONIS TOWER, 3. Stock, Wohnung/Büro 301A, 1070, Nikosia, Zypern. Intraservice Ltd erbringt konzerninterne Zahlungsdienstleistungen für und im Namen von BT Nexus Limited.",
    "faq.3.q": "Wie kann ich andere Fragen zu BrainTrade stellen?",
    "faq.3.a": "…",
    "faq.4.q": "Geht es bei BrainTrade nur um den Handel mit Kursen?",
    "faq.4.a": "…",
    "faq.5.q": "Wie unterscheidet sich BrainTrade vom Kauf eines beliebigen Handelskurses?",
    "faq.5.a": "…"
   },
   "ja": {
    "title": "よくある質問",
    "subtitle": "お手伝いできてうれしいです！ここでは、BrainTradeに関するよくある質問と疑問をまとめましたので、時間を節約できます。",
    "faq.0.q": "コースを始めるために前提となる経験は必要ですか？",
    "faq.0.a": "いいえ。コースを始めるために前提となる経験は必要ありません。BTは透明性を最も重視しており、私たちの目標は基本から始めて、教育プロセスを段階的に案内することです。",
    "faq.1.q": "パッケージをアップグレードするメリットは？",
    "faq.1.a": "…",
    "faq.2.q": "BrainTradeは安全ですか？",
    "faq.2.a": "はい。BrainTrade（www.thebraintrade.com）は、BT Nexus Limitedが運営するライセンス取得済みのプラットフォームです。当グループには、キプロス共和国の法律に基づき設立され存続する有限責任会社Intraservice Ltdが含まれます。登録住所は Arch. Makariou III, 73, METHONIS TOWER, 3rd Floor, Flat/Office 301A, 1070, Nicosia, Cyprus です。Intraservice Ltdは、BT Nexus Limitedのために、またその代理として、グループ内決済サービスを提供します。",
    "faq.3.q": "質問がある時はどうすればいいですか？",
    "faq.3.a": "…",
    "faq.4.q": "BrainTradeは取引コースだけのものですか？",
    "faq.4.a": "…",
    "faq.5.q": "BrainTradeは一般的な取引コースを購入するのとどう違うのですか？",
    "faq.5.a": "…"
   },
   "th": {
    "title": "คำถามที่พบบ่อย",
    "subtitle": "ยินดีที่จะช่วยเหลือ! นี่คือคำถามและข้อสงสัยที่พบบ่อยเกี่ยวกับ BrainTrade เพื่อช่วยประหยัดเวลาให้คุณ",
    "faq.0.q": "ต้องมีประสบการณ์มาก่อนถึงจะเริ่มเรียนได้ไหม?",
    "faq.0.a": "ไม่จำเป็นต้องมีประสบการณ์มาก่อน หลักสูตรของ BrainTrade เริ่มต้นจากพื้นฐาน เราให้ความสำคัญกับความโปร่งใสตั้งแต่ก้าวแรก และมุ่งมั่นที่จะแนะนำคุณผ่านกระบวนการเรียนรู้ทีละขั้นตอน",
    "faq.1.q": "ทำไมฉันถึงควรอัปเกรดแพ็กเกจกับ BrainTrade?",
    "faq.1.a": "…",
    "faq.2.q": "БrainTrade ปลอดภัยไหม?",
    "faq.2.a": "ใช่ BrainTrade (www.thebraintrade.com) เป็นแพลตฟอร์มที่ได้รับใบอนุญาต และดำเนินงานโดย BT Nexus Limited กลุ่มบริษัทประกอบด้วย Intraservice Ltd ซึ่งเป็นบริษัทจำกัดความรับผิด จัดตั้งและดำรงอยู่ภายใต้กฎหมายของสาธารณรัฐไซปรัส โดยมีที่อยู่จดทะเบียน Arch. Makariou III, 73, METHONIS TOWER, ชั้น 3, ห้อง/สำนักงาน 301A, 1070, นิโคเซีย, ไซปรัส Intraservice Ltd ให้บริการชำระเงินภายในกลุ่มสำหรับและในนามของ BT Nexus Limited",
    "faq.3.q": "ฉันจะสอบถามคำถามอื่นเกี่ยวกับ BrainTrade ได้อย่างไร?",
    "faq.3.a": "…",
    "faq.4.q": "BrainTrade ขายแค่หลักสูตรเท่านั้นใช่ไหม?",
    "faq.4.a": "…",
    "faq.5.q": "BrainTrade แตกต่างจากการซื้อหลักสูตรเทรดทั่วไปอย่างไร?",
    "faq.5.a": "…"
   },
   "vi": {
    "title": "Câu hỏi thường gặp",
    "subtitle": "Chúng tôi rất sẵn lòng hỗ trợ! Dưới đây là một số câu hỏi và thắc mắc phổ biến nhất về BrainTrade để giúp bạn tiết kiệm thời gian.",
    "faq.0.q": "Tôi có cần kinh nghiệm trước đó để bắt đầu các khóa học không?",
    "faq.0.a": "Không cần kinh nghiệm trước đó để bắt đầu các khóa học. BT coi trọng sự minh bạch trên hết, và mục tiêu của chúng tôi là hướng dẫn bạn qua quá trình giáo dục từng bước, bắt đầu từ những kiến thức cơ bản.",
    "faq.1.q": "Tại sao tôi nên nâng cấp gói dịch vụ với BrainTrade?",
    "faq.1.a": "…",
    "faq.2.q": "BrainTrade có an toàn không?",
    "faq.2.a": "Có. BrainTrade (www.thebraintrade.com) là một nền tảng được cấp phép, do BT Nexus Limited vận hành. Tập đoàn bao gồm Intraservice Ltd, một công ty trách nhiệm hữu hạn được thành lập và hoạt động theo pháp luật Cộng hòa Síp, có địa chỉ đăng ký tại Arch. Makariou III, 73, METHONIS TOWER, Tầng 3, Căn hộ/Văn phòng 301A, 1070, Nicosia, Síp. Intraservice Ltd cung cấp dịch vụ thanh toán nội bộ tập đoàn cho và thay mặt BT Nexus Limited.",
    "faq.3.q": "Làm thế nào tôi có thể hỏi thêm các câu hỏi khác về BrainTrade?",
    "faq.3.a": "…",
    "faq.4.q": "BrainTrade có chỉ là một nền tảng dạy giao dịch không?",
    "faq.4.a": "…",
    "faq.5.q": "BrainTrade khác gì so với việc mua một khóa học giao dịch ngẫu nhiên?",
    "faq.5.a": "…"
   },
   "ar": {
    "title": "الاسئلة المتداولة",
    "subtitle": "تسعدنا مساعدتك! إليك بعض من أكثر الأسئلة والاستفسارات تداولاً حول BrainTrade لتوفير وقتك.",
    "faq.0.q": "هل أحتاج إلى خبرة سابقة لبدء الدورات؟",
    "faq.0.a": "لا تتطلب الدورات خبرة سابقة. تقدر BT الشفافية فوق كل شيء، وهدفنا هو إرشادك خلال العملية التعليمية خطوة بخطوة، بدءًا من الأساسيات.",
    "faq.1.q": "لماذا يجب أن أرقّي باقتي مع BrainTrade؟",
    "faq.1.a": "…",
    "faq.2.q": "هل BrainTrade آمن؟",
    "faq.2.a": "نعم. BrainTrade (www.thebraintrade.com) منصة مرخصة تديرها شركة BT Nexus Limited. تشمل المجموعة شركة Intraservice Ltd، وهي شركة ذات مسؤولية محدودة مؤسسة وقائمة بموجب قوانين جمهورية قبرص، وعنوانها المسجل: Arch. Makariou III, 73, METHONIS TOWER, الطابق الثالث، شقة/مكتب 301A، 1070، نيقوسيا، قبرص. تقدم Intraservice Ltd خدمات دفع داخل المجموعة لصالح BT Nexus Limited وبالنيابة عنها.",
    "faq.3.q": "كيف يمكنني طرح أسئلة أخرى حول BrainTrade؟",
    "faq.3.a": "…",
    "faq.4.q": "هل BrainTrade يتعلق فقط بتداول الدورات التدريبية؟",
    "faq.4.a": "…",
    "faq.5.q": "كيف يختلف BrainTrade عن شراء دورة تداول عشوائية؟",
    "faq.5.a": "…"
   },
   "zh": {
    "title": "常见问题",
    "subtitle": "我们很高兴能帮助您！以下是一些关于BrainTrade的常见问题和查询，以节省您的时间。",
    "faq.0.q": "我需要先前的经验才能开始课程吗？",
    "faq.0.a": "不需要任何先前的经验就可以开始课程。BT最重视透明度，我们的目标是逐步引导您完成教育过程，从基础知识开始。",
    "faq.1.q": "我为什么要升级我的BrainTrade套餐？",
    "faq.1.a": "…",
    "faq.2.q": "BrainTrade安全吗？",
    "faq.2.a": "是的。BrainTrade（www.thebraintrade.com）是由 BT Nexus Limited 运营的持牌平台。集团包括 Intraservice Ltd，该公司为有限责任公司，依据塞浦路斯共和国法律注册成立并持续存续，注册地址为 Arch. Makariou III, 73, METHONIS TOWER, 3rd Floor, Flat/Office 301A, 1070, Nicosia, Cyprus。Intraservice Ltd 为 BT Nexus Limited 提供集团内部支付服务，并代表其开展相关支付服务。",
    "faq.3.q": "我如何询问有关BrainTrade的其他问题？",
    "faq.3.a": "…",
    "faq.4.q": "BrainTrade只是一个交易课程平台吗？",
    "faq.4.a": "…",
    "faq.5.q": "BrainTrade与购买普通交易课程有什么不同？",
    "faq.5.a": "…"
   }
  }
 },
 {
  "key": "bt-testimonials",
  "name": "BT / Testimonials",
  "category": "braintrade",
  "position": 260,
  "html": "<section class=\"lp-sec-bt-testimonials\">\n <div class=\"lp-wrap\">\n  <h2 class=\"btt-title\" data-lp-text=\"title\">A Word From Our Students</h2>\n  <p class=\"btt-sub\" data-lp-rich=\"subtitle\">Enough talk from our side. Here are the opinions that matter the most — your own.</p>\n  <div class=\"btt-grid\">\n   <!--lp-repeat:reviews--><div class=\"btt-card\"><div class=\"btt-head\"><img class=\"btt-avatar\" data-lp-img=\"photo\" src=\"\" alt=\"\"><div><p class=\"btt-name\" data-lp-text=\"name\">Jenny Wilson</p><p class=\"btt-role\" data-lp-text=\"role\">Customer Support Agent</p></div><span class=\"btt-mark\">”</span></div><p class=\"btt-quote\" data-lp-rich=\"quote\">BrainTrade really opened my eyes to how many opportunities show up in the markets every day.</p></div><!--/lp-repeat:reviews-->\n  </div>\n </div>\n</section>",
  "css": ".lp-sec-bt-testimonials{background:var(--lp-bg);padding:56px 0;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-testimonials .btt-title{color:var(--lp-accent);font-size:1.7rem;font-weight:700;margin:0 0 8px}\n.lp-sec-bt-testimonials .btt-sub{color:var(--lp-muted);margin:0 0 28px}\n.lp-sec-bt-testimonials .btt-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}\n.lp-sec-bt-testimonials .btt-card{background:#fff;border:1px solid #DDE1E6;border-radius:16px;padding:24px}\n.lp-sec-bt-testimonials .btt-head{display:flex;gap:12px;align-items:center;margin-bottom:14px}\n.lp-sec-bt-testimonials .btt-avatar{width:52px;height:52px;border-radius:999px;object-fit:cover;background:#F8D8CC}\n.lp-sec-bt-testimonials .btt-name{margin:0;font-weight:700;color:var(--lp-accent)}\n.lp-sec-bt-testimonials .btt-role{margin:2px 0 0;color:var(--lp-muted);font-size:.85rem}\n.lp-sec-bt-testimonials .btt-mark{margin-left:auto;color:var(--lp-primary);font-size:3rem;line-height:.6;font-weight:700}\n.lp-sec-bt-testimonials .btt-quote{color:var(--lp-muted);line-height:1.65;margin:0;font-size:.95rem}\n@media (max-width:575px){.lp-sec-bt-testimonials .btt-grid{grid-template-columns:1fr}}",
  "texts": {
   "en": {
    "title": "A Word From Our Students",
    "subtitle": "Enough talk from our side. Here are the opinions that matter the most - your own.",
    "reviews.0.name": "Jenny Wilson",
    "reviews.0.role": "Customer Support Agent",
    "reviews.0.quote": "BrainTrade really opened my eyes to how many opportunities show up in the markets every day. I started as a complete beginner and picked things up quickly because the video courses are clear, practical, and easy to follow. If you’re new to trading, I truly recommend it. It covers the fundamentals every beginner needs at the start of their journey.",
    "reviews.1.name": "Trevor Hawkins",
    "reviews.1.role": "Accountant",
    "reviews.1.quote": "Friends of mine bought me access to BrainTrade as a gift for my birthday and this was one of the coolest presents I have ever received. I started with the most basic courses and it was really a no-brainer from there, as I upgraded my package in almost a week. BrainTrade provides all the necessary knowledge and tools to navigate the financial markets and get the upper hand. I cannot thank my buddies enough for signing me up!"
   },
   "pt": {
    "title": "O que dizem nossos alunos",
    "subtitle": "Já falamos bastante. Agora a palavra é dos nossos alunos — as opiniões que realmente importam.",
    "reviews.0.name": "Fernanda Costa",
    "reviews.0.role": "Professora de História",
    "reviews.0.quote": "Como educadora, valorizo didática clara e apoio personalizado — e encontrei isso na BrainTrade. Os vídeos são objetivos e o Academy Trainer me ajudou sempre que travava em conceitos como risk-reward. Treinar sem pressão, com feedback direto do mentor, é libertador. Pra quem vem de outra área, é perfeito.",
    "reviews.1.name": "Rafael Lima",
    "reviews.1.role": "Engenheiro Civil",
    "reviews.1.quote": "Sempre achei o mercado financeiro abstrato — até conhecer o BrainTrade. O diferencial foi o mentor humano: responde em tempo real, corrige erros antes da conta real e ajuda a estruturar o pensamento. Conseguir aprender, praticar no simulador e operar com orientação — tudo em um só lugar — mudou tudo. á fiz minhas primeiras retiradas consistentes."
   },
   "ja": {
    "title": "ユーザーの声",
    "subtitle": "実際に学んだ人たちの本音をご紹介します。",
    "reviews.0.name": "佐藤 美咲",
    "reviews.0.role": "小学校教諭",
    "reviews.0.quote": "忙しい日常の中で、無理なく学べるのがBrainTradeの良い点です。特にメンターとのセッションは、私のペースに合わせて調整してくれて、理解が深まりました。知識→練習→フィードバックが一つのプラットフォームで完結するので、集中力が途切れません。初心者でも安心して一歩を踏み出せます。",
    "reviews.1.name": "田中 健太",
    "reviews.1.role": "システムエンジニア",
    "reviews.1.quote": "BrainTradeの最大の魅力は、経験豊富なメンターが丁寧に伴走してくれることです。動画で学び、シミュレーターで練習し、リアルなアドバイスをその都度受けられる――この一貫した流れが、私の成長を加速させました。以前は自己流で失敗ばかりでしたが、今ではルールに基づいた取引ができています。本当に感謝しています。"
   },
   "th": {
    "title": "คำจากนักเรียนของเรา",
    "subtitle": "ฟังจากเราพอแล้ว มาฟังความคิดเห็นที่สำคัญที่สุด – จากผู้ใช้จริง",
    "reviews.0.name": "พรรณิการ์ จันทร์หอม",
    "reviews.0.role": "ครูประถม",
    "reviews.0.quote": "ในฐานะคุณครูที่กำลังมองหารายได้เสริม BrainTrade ตอบโจทย์ได้ดีมาก วิดีโอกระชับ เนื้อหาตรงจุด เครื่องมือใช้งานง่ายและเชื่อมต่อกับแพลตฟอร์มจริง มีโค้ชคอยตอบคำถามตลอด เรียน-ฝึก-เทรดได้ลื่นไหลในที่เดียว ติดต่อง่าย แนะนำเลยค่ะ",
    "reviews.1.name": "สมชาย วงศ์สวัสดิ์",
    "reviews.1.role": "วิศวกรซอฟต์แวร์",
    "reviews.1.quote": "ชอบที่ BrainTrade ต่างจากแคมป์เทรดอื่นๆ ตรงที่ได้คำแนะนำจริงจากเมนเทอร์ ไม่ใช่แค่คอร์สวิดีโอ ฝึกในบัญชีทดลอง → เซ็ตอัพบัญชีจริง → เทรดจริงได้ภายใน 2 เดือน เมนเทอร์ตอบเอง ไม่ใช่ระบบอัตโนมัติ ตอบเร็วทุกครั้งจริงๆ ครับ"
   },
   "vi": {
    "title": "Lời chia sẻ từ học viên của chúng tôi",
    "subtitle": "Đã nói từ phía chúng tôi. Đây là những ý kiến quan trọng nhất - chính là của bạn.",
    "reviews.0.name": "Nguyễn Văn Hùng",
    "reviews.0.role": "Quản lý phân xưởng",
    "reviews.0.quote": "Điều khiến tôi tin tưởng BrainTrade là có mentor thật — không chỉ dạy lý thuyết mà còn hướng dẫn từng bước, từng chiến lược. Họ hiểu bối cảnh tài chính Việt Nam, không áp đặt mô hình nước ngoài. Cảm ơn đã ngồi dạy tôi từng bước và xây dựng hành trình học tập kiên nhẫn và có cấu trúc rõ ràng.",
    "reviews.1.name": "Trần Thị Mai",
    "reviews.1.role": "Giáo viên",
    "reviews.1.quote": "Là giáo viên, tôi cần trình bày sự rõ ràng khi học — và đó chính là điều tôi nhận được từ BrainTrade. Video ngắn gọn, dễ hiểu, đội ngũ mentor vừa lắng nghe và điều chỉnh tốc độ theo nhu cầu của tôi. Bài tập thực hành và câu hỏi ôn tập trong từng module rất rõ ràng. Tôi thực sự bắt đầu — điều mà trước đây tôi luôn trì hoãn."
   },
   "ar": {
    "title": "كلمة من طلابنا",
    "subtitle": "نكتفي بالكلام من جانبنا، وإليكم الجانب الأهم، وهو آراؤكم.",
    "reviews.0.name": "سارة خالد العلي",
    "reviews.0.role": "مدرسة ابتدائية",
    "reviews.0.quote": "كموظفة تعليمية، أقدّر جدًّا الوضوح والصبر — وهما ما وجدته في BrainTrade. الفيديوهات مختصرة ومُركّزة، والمرشدة تتفهّم ضغط وقتي وتُعدّل الجلسات حسب إتاحتي. الأهم أن العملية برمتها — التعلّم، المحاكاة، التغذية الراجعة — مترابطة بسلاسة في مكان واحد. شعرتُ أخيرًا أن البدء ممكن… وبأمان.",
    "reviews.1.name": "أحمد محمد عبد الله",
    "reviews.1.role": "مهندس برمجيات",
    "reviews.1.quote": "ما يميّز BrainTrade حقًا هو وجود مرشد بشري يرافقك خطوة بخطوة — ليس فقط في الشرح، بل في التصحيح الفعلي أثناء التدريب على المحاكاة. تعلّمت → تدرّبت → تلقيت ملاحظات مباشرة، وكل ذلك في منصة واحدة. خلال شهرين، تحولت من التداول العشوائي إلى اتباع خطة واضحة. شكرًا للفريق على هذا الدعم الملموس."
   },
   "zh": {
    "title": "来自我们学生的一句话",
    "subtitle": "不再多说，这里是最重要的意见——你自己的意见。",
    "reviews.0.name": "珍妮·威尔逊",
    "reviews.0.role": "客户支持专员",
    "reviews.0.quote": "BrainTrade 让我意识到市场每天都有多少机会。我从一个完全的初学者开始，快速掌握了知识，因为视频课程清晰、实用且容易上手。如果你是交易新手，我真的推荐它。它涵盖了每个初学者在旅程开始时所需的基础知识。",
    "reviews.1.name": "王伟",
    "reviews.1.role": "软件工程师",
    "reviews.1.quote": "BrainTrade最打动我的，是真人导师全程陪伴——不只是讲课，更会在模拟交易中实时指出问题。学→练→改，三步闭环全在同一个平台完成。两个月内，我从情绪化下单，转变为严格执行交易计划。真心感谢团队打造了这样一条清晰、有人引路的成长路径。"
   },
   "it": {
    "title": "La parola ai nostri studenti",
    "subtitle": "Non fidarti solo di noi. Ecco le opinioni che contano di più: quelle dei nostri studenti.",
    "reviews.0.name": "Martina Bellucci",
    "reviews.0.role": "Consulente finanziaria",
    "reviews.0.quote": "BrainTrade mi ha aiutata a capire finalmente come funziona il mondo dei mercati. Le lezioni sono guidate passo dopo passo e il supporto del mio mentore ha reso tutto molto più chiaro. Non promette miracoli, ma ti dà una solida base per muoverti con sicurezza.",
    "reviews.1.name": "Luca Ferraro",
    "reviews.1.role": "Ingegnere informatico",
    "reviews.1.quote": "Prima di BrainTrade avevo le idee confuse. Adesso ho un percorso chiaro: studio, pratica e poi, con calma, applicazione reale. Le spiegazioni sono semplici ma professionali, e avere qualcuno che ti segue personalmente fa davvero la differenza."
   },
   "pl": {
    "title": "Głos naszych studentów",
    "subtitle": "Nie wierz nam na słowo — oto opinie, które liczą się najbardziej: te od naszych studentów.",
    "reviews.0.name": "Anna Wójcik",
    "reviews.0.role": "Analityczka danych",
    "reviews.0.quote": "Zawsze chciałam lepiej zrozumieć finanse, ale nie wiedziałam, od czego zacząć. BrainTrade dało mi jasną ścieżkę nauki i coacha, który tłumaczy wszystko krok po kroku.",
    "reviews.1.name": "Piotr Lewandowski",
    "reviews.1.role": "Specjalista ds. marketingu",
    "reviews.1.quote": "BrainTrade dało mi strukturę, której wcześniej brakowało. Teraz mam plan nauki: teoria, ćwiczenia i dopiero potem praktyczne zastosowanie. Coach pomaga mi zachować dyscyplinę i uczyć się odpowiedzialnie."
   },
   "sv": {
    "title": "Vad våra studenter säger",
    "subtitle": "Vi har sagt nog. Nu får våra studenter ordet.",
    "reviews.0.name": "Sara Lindström",
    "reviews.0.role": "Marknadsföringsspecialist",
    "reviews.0.quote": "Jag har länge velat förstå hur marknaderna fungerar, men visste aldrig var jag skulle börja. BrainTrade gav mig en tydlig väg framåt och en mentor som verkligen förklarade steg för steg. Nu känner jag mig mycket tryggare i mina beslut.",
    "reviews.1.name": "Erik Holmgren",
    "reviews.1.role": "Ekonomikonsult",
    "reviews.1.quote": "BrainTrade gav mig den struktur jag saknat. Tydliga videokurser, praktiska övningar och en mentor som faktiskt lyssnar. Det här är en utbildning som handlar om kunskap, inte snabba genvägar."
   },
   "fr": {
    "title": "Un mot de nos étudiants",
    "subtitle": "Assez parlé de notre part. Voici les opinions qui comptent le plus - les vôtres.",
    "reviews.0.name": "Camille Laurent",
    "reviews.0.role": "Analyste de données",
    "reviews.0.quote": "Je cherchais une plateforme qui m’explique vraiment comment fonctionnent les marchés, sans jargon inutile. BrainTrade m’a donné exactement ça. Les cours sont progressifs, et mon mentor m’a aidée à comprendre des notions que je pensais trop compliquées.",
    "reviews.1.name": "Thomas Lefèvre",
    "reviews.1.role": "Conseiller financier",
    "reviews.1.quote": "Avant BrainTrade, j’étais complètement perdue face à la finance. Maintenant, j’ai une vraie méthode et je comprends ce que je fais. La plateforme m’a donné la structure dont j’avais besoin pour apprendre sérieusement."
   },
   "de": {
    "title": "Ein Wort von unseren Studenten",
    "subtitle": "Genug geredet von unserer Seite. Hier sind die Meinungen, die am meisten zählen - Ihre eigenen.",
    "reviews.0.name": "Anna Schneider",
    "reviews.0.role": "Finanzberater",
    "reviews.0.quote": "Ich hatte nie das Gefühl, die Finanzwelt wirklich zu verstehen, bis ich mit BrainTrade angefangen habe. Mein Mentor hat mir geholfen, die Grundlagen sauber aufzubauen, und die Lernplattform macht alles Schritt für Schritt nachvollziehbar. Eine großartige Unterstützung für Einsteiger.",
    "reviews.1.name": "Lukas Weber",
    "reviews.1.role": "Softwareentwickler",
    "reviews.1.quote": "Ich war skeptisch, ob Trading überhaupt etwas für mich ist. Durch BrainTrade habe ich gemerkt, dass es in erster Linie um Wissen, Planung und Risikobewusstsein geht. Die Plattform bringt genau diese Themen klar und praxisnah rüber."
   }
  }
 },
 {
  "key": "bt-footer",
  "name": "BT / Footer",
  "category": "braintrade",
  "position": 265,
  "html": "<section class=\"lp-sec-bt-footer\">\n <div class=\"lp-wrap btft-inner\">\n  <nav class=\"btft-links\">\n   <a data-lp-link=\"privacy_href\" data-lp-text=\"link_privacy\" href=\"#\">Privacy Policy</a>\n   <a data-lp-link=\"contact_href\" data-lp-text=\"link_contact\" href=\"#\">Contact Us</a>\n   <a data-lp-link=\"terms_href\" data-lp-text=\"link_terms\" href=\"#\">Terms and Conditions</a>\n  </nav>\n  <p class=\"btft-legal\" data-lp-rich=\"legal\">BrainTrade (www.thebraintrade.com) is operated by RT Nexus Limited. Please read the terms, privacy policy and cookie policy before proceeding.</p>\n  <p class=\"btft-copy\" data-lp-text=\"copyright\">© 2026 All right reserved.</p>\n </div>\n</section>",
  "css": ".lp-sec-bt-footer{background:var(--lp-bg);padding:40px 0 28px;font-family:'Urbanist',var(--lp-font)}\n.lp-sec-bt-footer .btft-inner{text-align:center}\n.lp-sec-bt-footer .btft-links{display:flex;justify-content:center;gap:28px;margin-bottom:18px;flex-wrap:wrap}\n.lp-sec-bt-footer .btft-links a{color:var(--lp-accent);text-decoration:none;font-size:.9rem;font-weight:500}\n.lp-sec-bt-footer .btft-legal{color:var(--lp-muted);font-size:.8rem;line-height:1.6;max-width:720px;margin:0 auto 10px}\n.lp-sec-bt-footer .btft-copy{color:var(--lp-muted);font-size:.78rem;margin:0}",
  "texts": {
   "en": {}
  }
 }
]
